import type { SyntheticUserProfile, SyntheticBehaviorModel } from './types'
import type { UserProfileVector } from '@linguaflow/feature-space'

export const HIGH_COMPREHENSION_LOW_PATIENCE: SyntheticUserProfile = {
  id: 'high_comp_low_patience',
  name: 'High Comprehension, Low Patience',
  description: 'Understands well but gets bored easily. Will skip if not challenged.',
  profile: {
    speedTolerance: 0.8,
    vocabularyBreadth: 0.7,
    grammarFamiliarity: 0.7,
    subtitleReliance: 0.2,
    contextInference: 0.7,
    emotionalReceptivity: 0.5,
    narrativeFollowing: 0.6,
    sceneProcessing: 0.6,
    accentAdaptability: 0.5,
    abstractionCapacity: 0.6,
  },
  behavior: {
    pauseProbability: 0.02,
    replayProbability: 0.01,
    subtitleToggleProbability: 0.01,
    skipProbability: 0.15,
    abandonProbability: 0.08,
    speedPreference: 1.3,
    fatigueRate: 0.008,
    recoveryRate: 0.01,
    comprehensionDecayRate: 0.001,
    immersionGrowthRate: 0.005,
  },
}

export const HIGH_IMMERSION_EASY_FATIGUE: SyntheticUserProfile = {
  id: 'high_immersion_easy_fatigue',
  name: 'High Immersion, Easy Fatigue',
  description: 'Gets deeply immersed but burns out quickly. Needs rest management.',
  profile: {
    speedTolerance: 0.4,
    vocabularyBreadth: 0.4,
    grammarFamiliarity: 0.4,
    subtitleReliance: 0.5,
    contextInference: 0.5,
    emotionalReceptivity: 0.9,
    narrativeFollowing: 0.8,
    sceneProcessing: 0.4,
    accentAdaptability: 0.3,
    abstractionCapacity: 0.3,
  },
  behavior: {
    pauseProbability: 0.05,
    replayProbability: 0.03,
    subtitleToggleProbability: 0.04,
    skipProbability: 0.02,
    abandonProbability: 0.05,
    speedPreference: 1.0,
    fatigueRate: 0.02,
    recoveryRate: 0.005,
    comprehensionDecayRate: 0.003,
    immersionGrowthRate: 0.01,
  },
}

export const SUBTITLE_DEPENDENT: SyntheticUserProfile = {
  id: 'subtitle_dependent',
  name: 'Subtitle Dependent',
  description: 'Relies heavily on subtitles. Panics when subtitles are off.',
  profile: {
    speedTolerance: 0.3,
    vocabularyBreadth: 0.3,
    grammarFamiliarity: 0.3,
    subtitleReliance: 0.9,
    contextInference: 0.3,
    emotionalReceptivity: 0.5,
    narrativeFollowing: 0.4,
    sceneProcessing: 0.3,
    accentAdaptability: 0.2,
    abstractionCapacity: 0.2,
  },
  behavior: {
    pauseProbability: 0.1,
    replayProbability: 0.08,
    subtitleToggleProbability: 0.15,
    skipProbability: 0.05,
    abandonProbability: 0.1,
    speedPreference: 0.8,
    fatigueRate: 0.005,
    recoveryRate: 0.008,
    comprehensionDecayRate: 0.004,
    immersionGrowthRate: 0.003,
  },
}

export const EXPLORATION_TYPE: SyntheticUserProfile = {
  id: 'exploration_type',
  name: 'Exploration Type',
  description: 'Wants variety. Will skip content that feels repetitive.',
  profile: {
    speedTolerance: 0.5,
    vocabularyBreadth: 0.5,
    grammarFamiliarity: 0.5,
    subtitleReliance: 0.4,
    contextInference: 0.6,
    emotionalReceptivity: 0.6,
    narrativeFollowing: 0.5,
    sceneProcessing: 0.5,
    accentAdaptability: 0.4,
    abstractionCapacity: 0.5,
  },
  behavior: {
    pauseProbability: 0.03,
    replayProbability: 0.02,
    subtitleToggleProbability: 0.03,
    skipProbability: 0.1,
    abandonProbability: 0.03,
    speedPreference: 1.1,
    fatigueRate: 0.004,
    recoveryRate: 0.01,
    comprehensionDecayRate: 0.002,
    immersionGrowthRate: 0.006,
  },
}

export const ANXIETY_TYPE: SyntheticUserProfile = {
  id: 'anxiety_type',
  name: 'Anxiety Type',
  description: 'Easily stressed by difficulty. Needs gentle adaptation.',
  profile: {
    speedTolerance: 0.2,
    vocabularyBreadth: 0.2,
    grammarFamiliarity: 0.2,
    subtitleReliance: 0.8,
    contextInference: 0.2,
    emotionalReceptivity: 0.7,
    narrativeFollowing: 0.3,
    sceneProcessing: 0.2,
    accentAdaptability: 0.1,
    abstractionCapacity: 0.1,
  },
  behavior: {
    pauseProbability: 0.15,
    replayProbability: 0.12,
    subtitleToggleProbability: 0.1,
    skipProbability: 0.08,
    abandonProbability: 0.15,
    speedPreference: 0.7,
    fatigueRate: 0.015,
    recoveryRate: 0.003,
    comprehensionDecayRate: 0.005,
    immersionGrowthRate: 0.002,
  },
}

export const COMPLETION_OBSESSIVE: SyntheticUserProfile = {
  id: 'completion_obsessive',
  name: 'Completion Obsessive',
  description: 'Must finish everything. Will power through even when not understanding.',
  profile: {
    speedTolerance: 0.5,
    vocabularyBreadth: 0.4,
    grammarFamiliarity: 0.4,
    subtitleReliance: 0.5,
    contextInference: 0.4,
    emotionalReceptivity: 0.4,
    narrativeFollowing: 0.6,
    sceneProcessing: 0.4,
    accentAdaptability: 0.3,
    abstractionCapacity: 0.3,
  },
  behavior: {
    pauseProbability: 0.03,
    replayProbability: 0.02,
    subtitleToggleProbability: 0.02,
    skipProbability: 0.01,
    abandonProbability: 0.01,
    speedPreference: 1.0,
    fatigueRate: 0.006,
    recoveryRate: 0.006,
    comprehensionDecayRate: 0.002,
    immersionGrowthRate: 0.004,
  },
}

export const ALL_PROFILES: SyntheticUserProfile[] = [
  HIGH_COMPREHENSION_LOW_PATIENCE,
  HIGH_IMMERSION_EASY_FATIGUE,
  SUBTITLE_DEPENDENT,
  EXPLORATION_TYPE,
  ANXIETY_TYPE,
  COMPLETION_OBSESSIVE,
]
