import type { ContentFeatureVector } from '@linguaflow/feature-space'

interface SeedContentItem {
  title: string
  description: string
  language: 'en'
  level: number
  videoUrl: string
  thumbnailUrl: string
  subtitleUrl: string
  durationSeconds: number
  features: ContentFeatureVector
  tags: string[]
}

const level0Items: SeedContentItem[] = [
  {
    title: 'My Morning Routine',
    description: 'Follow Sarah through her morning routine from waking up to leaving for school. Simple present tense with clear visuals.',
    language: 'en',
    level: 0,
    videoUrl: 'https://cdn.linguaflow.dev/content/001/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/001/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/001/subtitles.vtt',
    durationSeconds: 45,
    features: { speechSpeed: 0.22, lexicalNovelty: 0.06, grammarDensity: 0.07, subtitleDependency: 0.75, visualContextStrength: 0.90, emotionalIntensity: 0.45, narrativeDependency: 0.12, sceneComplexity: 0.12, accentDistance: 0.06, abstractionLevel: 0.06 },
    tags: ['daily-routine', 'beginner', 'present-tense'],
  },
  {
    title: 'Making Breakfast',
    description: 'Learn food vocabulary as Chef Tom prepares a simple breakfast. Each ingredient is shown on screen with labels.',
    language: 'en',
    level: 0,
    videoUrl: 'https://cdn.linguaflow.dev/content/002/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/002/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/002/subtitles.vtt',
    durationSeconds: 60,
    features: { speechSpeed: 0.25, lexicalNovelty: 0.08, grammarDensity: 0.08, subtitleDependency: 0.70, visualContextStrength: 0.92, emotionalIntensity: 0.50, narrativeDependency: 0.15, sceneComplexity: 0.14, accentDistance: 0.07, abstractionLevel: 0.07 },
    tags: ['food', 'cooking', 'vocabulary'],
  },
  {
    title: 'At the Zoo',
    description: 'Visit the zoo and learn the names of popular animals. Each animal is introduced with a clear video clip and slow narration.',
    language: 'en',
    level: 0,
    videoUrl: 'https://cdn.linguaflow.dev/content/003/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/003/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/003/subtitles.vtt',
    durationSeconds: 90,
    features: { speechSpeed: 0.24, lexicalNovelty: 0.10, grammarDensity: 0.06, subtitleDependency: 0.72, visualContextStrength: 0.95, emotionalIntensity: 0.60, narrativeDependency: 0.10, sceneComplexity: 0.11, accentDistance: 0.05, abstractionLevel: 0.05 },
    tags: ['animals', 'zoo', 'vocabulary'],
  },
  {
    title: 'Colors All Around Us',
    description: 'Explore colors in everyday objects. Red apples, blue skies, green grass — each color is highlighted with vivid imagery.',
    language: 'en',
    level: 0,
    videoUrl: 'https://cdn.linguaflow.dev/content/004/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/004/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/004/subtitles.vtt',
    durationSeconds: 35,
    features: { speechSpeed: 0.20, lexicalNovelty: 0.05, grammarDensity: 0.05, subtitleDependency: 0.78, visualContextStrength: 0.94, emotionalIntensity: 0.42, narrativeDependency: 0.10, sceneComplexity: 0.10, accentDistance: 0.06, abstractionLevel: 0.05 },
    tags: ['colors', 'shapes', 'vocabulary'],
  },
  {
    title: 'Hello and Goodbye',
    description: 'Practice common greetings in different situations. From meeting friends to saying goodbye at the end of the day.',
    language: 'en',
    level: 0,
    videoUrl: 'https://cdn.linguaflow.dev/content/005/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/005/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/005/subtitles.vtt',
    durationSeconds: 40,
    features: { speechSpeed: 0.23, lexicalNovelty: 0.07, grammarDensity: 0.06, subtitleDependency: 0.76, visualContextStrength: 0.88, emotionalIntensity: 0.55, narrativeDependency: 0.14, sceneComplexity: 0.13, accentDistance: 0.08, abstractionLevel: 0.06 },
    tags: ['greetings', 'social', 'beginner'],
  },
  {
    title: 'Counting to Twenty',
    description: 'Learn numbers from one to twenty with fun visual counting exercises. Each number is displayed on screen and repeated clearly.',
    language: 'en',
    level: 0,
    videoUrl: 'https://cdn.linguaflow.dev/content/006/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/006/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/006/subtitles.vtt',
    durationSeconds: 50,
    features: { speechSpeed: 0.21, lexicalNovelty: 0.06, grammarDensity: 0.05, subtitleDependency: 0.80, visualContextStrength: 0.93, emotionalIntensity: 0.48, narrativeDependency: 0.10, sceneComplexity: 0.10, accentDistance: 0.05, abstractionLevel: 0.08 },
    tags: ['numbers', 'counting', 'basics'],
  },
  {
    title: 'What Is the Weather Today?',
    description: 'Sunny, rainy, snowy, or windy — learn weather words with beautiful footage of each condition.',
    language: 'en',
    level: 0,
    videoUrl: 'https://cdn.linguaflow.dev/content/007/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/007/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/007/subtitles.vtt',
    durationSeconds: 55,
    features: { speechSpeed: 0.26, lexicalNovelty: 0.09, grammarDensity: 0.08, subtitleDependency: 0.68, visualContextStrength: 0.91, emotionalIntensity: 0.50, narrativeDependency: 0.12, sceneComplexity: 0.15, accentDistance: 0.07, abstractionLevel: 0.07 },
    tags: ['weather', 'nature', 'vocabulary'],
  },
  {
    title: 'My Family',
    description: 'Meet the Johnson family and learn words for mother, father, sister, brother, and more. Simple introductions for each member.',
    language: 'en',
    level: 0,
    videoUrl: 'https://cdn.linguaflow.dev/content/008/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/008/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/008/subtitles.vtt',
    durationSeconds: 65,
    features: { speechSpeed: 0.24, lexicalNovelty: 0.08, grammarDensity: 0.07, subtitleDependency: 0.74, visualContextStrength: 0.87, emotionalIntensity: 0.58, narrativeDependency: 0.18, sceneComplexity: 0.14, accentDistance: 0.06, abstractionLevel: 0.06 },
    tags: ['family', 'relationships', 'beginner'],
  },
  {
    title: 'Head, Shoulders, Knees, and Toes',
    description: 'Learn body parts through the classic song with animated characters pointing to each part as it is named.',
    language: 'en',
    level: 0,
    videoUrl: 'https://cdn.linguaflow.dev/content/009/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/009/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/009/subtitles.vtt',
    durationSeconds: 30,
    features: { speechSpeed: 0.22, lexicalNovelty: 0.07, grammarDensity: 0.05, subtitleDependency: 0.79, visualContextStrength: 0.96, emotionalIntensity: 0.65, narrativeDependency: 0.10, sceneComplexity: 0.10, accentDistance: 0.05, abstractionLevel: 0.05 },
    tags: ['body-parts', 'song', 'vocabulary'],
  },
  {
    title: 'Getting Dressed',
    description: 'Watch Emma pick out her outfit for the day. Learn words for shirt, pants, shoes, hat, and jacket with clear visuals.',
    language: 'en',
    level: 0,
    videoUrl: 'https://cdn.linguaflow.dev/content/010/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/010/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/010/subtitles.vtt',
    durationSeconds: 50,
    features: { speechSpeed: 0.25, lexicalNovelty: 0.09, grammarDensity: 0.07, subtitleDependency: 0.71, visualContextStrength: 0.89, emotionalIntensity: 0.47, narrativeDependency: 0.15, sceneComplexity: 0.13, accentDistance: 0.07, abstractionLevel: 0.06 },
    tags: ['clothing', 'daily-routine', 'vocabulary'],
  },
  {
    title: 'In the Kitchen',
    description: 'Explore kitchen vocabulary — plate, cup, fork, spoon, and more. Each item is shown in a real kitchen setting.',
    language: 'en',
    level: 0,
    videoUrl: 'https://cdn.linguaflow.dev/content/011/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/011/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/011/subtitles.vtt',
    durationSeconds: 55,
    features: { speechSpeed: 0.27, lexicalNovelty: 0.10, grammarDensity: 0.08, subtitleDependency: 0.69, visualContextStrength: 0.91, emotionalIntensity: 0.44, narrativeDependency: 0.13, sceneComplexity: 0.16, accentDistance: 0.08, abstractionLevel: 0.07 },
    tags: ['food', 'kitchen', 'vocabulary'],
  },
  {
    title: 'Farm Animals',
    description: 'Visit a farm and meet cows, chickens, pigs, and sheep. Each animal makes its sound as its name is introduced.',
    language: 'en',
    level: 0,
    videoUrl: 'https://cdn.linguaflow.dev/content/012/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/012/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/012/subtitles.vtt',
    durationSeconds: 70,
    features: { speechSpeed: 0.23, lexicalNovelty: 0.08, grammarDensity: 0.06, subtitleDependency: 0.73, visualContextStrength: 0.94, emotionalIntensity: 0.62, narrativeDependency: 0.11, sceneComplexity: 0.12, accentDistance: 0.06, abstractionLevel: 0.05 },
    tags: ['animals', 'farm', 'vocabulary'],
  },
  {
    title: 'Shapes in the City',
    description: 'Find circles, squares, triangles, and rectangles in city buildings and signs. A visual tour of geometry in everyday life.',
    language: 'en',
    level: 0,
    videoUrl: 'https://cdn.linguaflow.dev/content/013/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/013/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/013/subtitles.vtt',
    durationSeconds: 45,
    features: { speechSpeed: 0.21, lexicalNovelty: 0.06, grammarDensity: 0.06, subtitleDependency: 0.77, visualContextStrength: 0.93, emotionalIntensity: 0.43, narrativeDependency: 0.12, sceneComplexity: 0.18, accentDistance: 0.07, abstractionLevel: 0.09 },
    tags: ['shapes', 'city', 'vocabulary'],
  },
  {
    title: 'Saying Thank You',
    description: 'Learn polite expressions like thank you, please, and excuse me through everyday scenarios at a store and restaurant.',
    language: 'en',
    level: 0,
    videoUrl: 'https://cdn.linguaflow.dev/content/014/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/014/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/014/subtitles.vtt',
    durationSeconds: 48,
    features: { speechSpeed: 0.25, lexicalNovelty: 0.07, grammarDensity: 0.07, subtitleDependency: 0.72, visualContextStrength: 0.86, emotionalIntensity: 0.52, narrativeDependency: 0.16, sceneComplexity: 0.14, accentDistance: 0.08, abstractionLevel: 0.06 },
    tags: ['greetings', 'polite-expressions', 'social'],
  },
  {
    title: 'Numbers at the Store',
    description: 'Practice numbers while shopping for fruit. How many apples? How much is it? Basic counting and price language.',
    language: 'en',
    level: 0,
    videoUrl: 'https://cdn.linguaflow.dev/content/015/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/015/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/015/subtitles.vtt',
    durationSeconds: 60,
    features: { speechSpeed: 0.28, lexicalNovelty: 0.11, grammarDensity: 0.09, subtitleDependency: 0.67, visualContextStrength: 0.88, emotionalIntensity: 0.46, narrativeDependency: 0.17, sceneComplexity: 0.17, accentDistance: 0.09, abstractionLevel: 0.08 },
    tags: ['numbers', 'shopping', 'basics'],
  },
  {
    title: 'Rainy Day Fun',
    description: 'It is raining outside. Learn weather words and indoor activity vocabulary as kids play inside on a rainy day.',
    language: 'en',
    level: 0,
    videoUrl: 'https://cdn.linguaflow.dev/content/016/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/016/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/016/subtitles.vtt',
    durationSeconds: 55,
    features: { speechSpeed: 0.24, lexicalNovelty: 0.09, grammarDensity: 0.07, subtitleDependency: 0.70, visualContextStrength: 0.90, emotionalIntensity: 0.56, narrativeDependency: 0.20, sceneComplexity: 0.15, accentDistance: 0.06, abstractionLevel: 0.07 },
    tags: ['weather', 'activities', 'vocabulary'],
  },
  {
    title: 'My Big Brother',
    description: 'A short story about a girl and her older brother. Learn family words and simple action verbs in context.',
    language: 'en',
    level: 0,
    videoUrl: 'https://cdn.linguaflow.dev/content/017/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/017/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/017/subtitles.vtt',
    durationSeconds: 80,
    features: { speechSpeed: 0.26, lexicalNovelty: 0.10, grammarDensity: 0.09, subtitleDependency: 0.68, visualContextStrength: 0.85, emotionalIntensity: 0.60, narrativeDependency: 0.22, sceneComplexity: 0.16, accentDistance: 0.07, abstractionLevel: 0.07 },
    tags: ['family', 'story', 'action-verbs'],
  },
  {
    title: 'Wash Your Hands',
    description: 'Step-by-step instructions for washing hands. Learn body part and action words with a clear visual sequence.',
    language: 'en',
    level: 0,
    videoUrl: 'https://cdn.linguaflow.dev/content/018/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/018/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/018/subtitles.vtt',
    durationSeconds: 35,
    features: { speechSpeed: 0.22, lexicalNovelty: 0.06, grammarDensity: 0.06, subtitleDependency: 0.76, visualContextStrength: 0.92, emotionalIntensity: 0.44, narrativeDependency: 0.14, sceneComplexity: 0.11, accentDistance: 0.05, abstractionLevel: 0.06 },
    tags: ['body-parts', 'daily-routine', 'health'],
  },
  {
    title: 'What Are You Wearing?',
    description: 'A guessing game where you identify clothing items from clues. Reinforces clothing vocabulary with interactive visuals.',
    language: 'en',
    level: 0,
    videoUrl: 'https://cdn.linguaflow.dev/content/019/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/019/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/019/subtitles.vtt',
    durationSeconds: 65,
    features: { speechSpeed: 0.29, lexicalNovelty: 0.12, grammarDensity: 0.10, subtitleDependency: 0.65, visualContextStrength: 0.87, emotionalIntensity: 0.54, narrativeDependency: 0.18, sceneComplexity: 0.18, accentDistance: 0.08, abstractionLevel: 0.08 },
    tags: ['clothing', 'game', 'questions'],
  },
  {
    title: 'Dinner Time',
    description: 'The family sits down for dinner. Learn food and table vocabulary with clear labels on every dish and utensil.',
    language: 'en',
    level: 0,
    videoUrl: 'https://cdn.linguaflow.dev/content/020/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/020/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/020/subtitles.vtt',
    durationSeconds: 70,
    features: { speechSpeed: 0.25, lexicalNovelty: 0.09, grammarDensity: 0.08, subtitleDependency: 0.71, visualContextStrength: 0.89, emotionalIntensity: 0.57, narrativeDependency: 0.19, sceneComplexity: 0.15, accentDistance: 0.07, abstractionLevel: 0.06 },
    tags: ['food', 'family', 'dinner'],
  },
]

const level1Items: SeedContentItem[] = [
  {
    title: 'At the Grocery Store',
    description: 'Follow Maria as she shops for groceries. Learn shopping vocabulary, asking for items, and understanding prices.',
    language: 'en',
    level: 1,
    videoUrl: 'https://cdn.linguaflow.dev/content/021/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/021/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/021/subtitles.vtt',
    durationSeconds: 120,
    features: { speechSpeed: 0.38, lexicalNovelty: 0.16, grammarDensity: 0.16, subtitleDependency: 0.55, visualContextStrength: 0.72, emotionalIntensity: 0.45, narrativeDependency: 0.22, sceneComplexity: 0.22, accentDistance: 0.12, abstractionLevel: 0.12 },
    tags: ['shopping', 'food', 'conversation'],
  },
  {
    title: 'How Do I Get There?',
    description: 'Learn to ask for and give directions. Walk through a neighborhood following turn-by-turn instructions.',
    language: 'en',
    level: 1,
    videoUrl: 'https://cdn.linguaflow.dev/content/022/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/022/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/022/subtitles.vtt',
    durationSeconds: 100,
    features: { speechSpeed: 0.40, lexicalNovelty: 0.18, grammarDensity: 0.18, subtitleDependency: 0.52, visualContextStrength: 0.70, emotionalIntensity: 0.42, narrativeDependency: 0.25, sceneComplexity: 0.25, accentDistance: 0.14, abstractionLevel: 0.14 },
    tags: ['directions', 'navigation', 'city'],
  },
  {
    title: 'My Favorite Hobby',
    description: 'Several people describe their hobbies — painting, cycling, reading, and gardening. Learn to talk about leisure activities.',
    language: 'en',
    level: 1,
    videoUrl: 'https://cdn.linguaflow.dev/content/023/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/023/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/023/subtitles.vtt',
    durationSeconds: 150,
    features: { speechSpeed: 0.42, lexicalNovelty: 0.20, grammarDensity: 0.20, subtitleDependency: 0.48, visualContextStrength: 0.68, emotionalIntensity: 0.55, narrativeDependency: 0.28, sceneComplexity: 0.28, accentDistance: 0.15, abstractionLevel: 0.15 },
    tags: ['hobbies', 'leisure', 'conversation'],
  },
  {
    title: 'First Day at School',
    description: 'Experience a student\'s first day at a new school. Classroom vocabulary, introductions, and following instructions.',
    language: 'en',
    level: 1,
    videoUrl: 'https://cdn.linguaflow.dev/content/024/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/024/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/024/subtitles.vtt',
    durationSeconds: 180,
    features: { speechSpeed: 0.39, lexicalNovelty: 0.17, grammarDensity: 0.17, subtitleDependency: 0.54, visualContextStrength: 0.65, emotionalIntensity: 0.60, narrativeDependency: 0.30, sceneComplexity: 0.26, accentDistance: 0.13, abstractionLevel: 0.13 },
    tags: ['school', 'education', 'social'],
  },
  {
    title: 'Soccer Practice',
    description: 'Join a youth soccer team at practice. Learn sports vocabulary, action verbs, and encouraging expressions.',
    language: 'en',
    level: 1,
    videoUrl: 'https://cdn.linguaflow.dev/content/025/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/025/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/025/subtitles.vtt',
    durationSeconds: 140,
    features: { speechSpeed: 0.44, lexicalNovelty: 0.19, grammarDensity: 0.19, subtitleDependency: 0.46, visualContextStrength: 0.74, emotionalIntensity: 0.65, narrativeDependency: 0.24, sceneComplexity: 0.30, accentDistance: 0.16, abstractionLevel: 0.14 },
    tags: ['sports', 'soccer', 'teamwork'],
  },
  {
    title: 'Happy Birthday!',
    description: 'Celebrate a birthday party from setting up to blowing out candles. Learn holiday and celebration vocabulary.',
    language: 'en',
    level: 1,
    videoUrl: 'https://cdn.linguaflow.dev/content/026/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/026/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/026/subtitles.vtt',
    durationSeconds: 110,
    features: { speechSpeed: 0.37, lexicalNovelty: 0.15, grammarDensity: 0.16, subtitleDependency: 0.56, visualContextStrength: 0.73, emotionalIntensity: 0.68, narrativeDependency: 0.26, sceneComplexity: 0.24, accentDistance: 0.11, abstractionLevel: 0.11 },
    tags: ['holidays', 'celebration', 'party'],
  },
  {
    title: 'Visiting the Doctor',
    description: 'A routine check-up at the doctor\'s office. Learn health vocabulary, describing symptoms, and understanding instructions.',
    language: 'en',
    level: 1,
    videoUrl: 'https://cdn.linguaflow.dev/content/027/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/027/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/027/subtitles.vtt',
    durationSeconds: 160,
    features: { speechSpeed: 0.41, lexicalNovelty: 0.22, grammarDensity: 0.21, subtitleDependency: 0.50, visualContextStrength: 0.62, emotionalIntensity: 0.48, narrativeDependency: 0.32, sceneComplexity: 0.27, accentDistance: 0.14, abstractionLevel: 0.18 },
    tags: ['health', 'doctor', 'conversation'],
  },
  {
    title: 'Taking the Bus',
    description: 'Navigate public transportation from buying a ticket to finding your stop. Learn transit vocabulary and time expressions.',
    language: 'en',
    level: 1,
    videoUrl: 'https://cdn.linguaflow.dev/content/028/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/028/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/028/subtitles.vtt',
    durationSeconds: 130,
    features: { speechSpeed: 0.40, lexicalNovelty: 0.18, grammarDensity: 0.18, subtitleDependency: 0.53, visualContextStrength: 0.66, emotionalIntensity: 0.43, narrativeDependency: 0.28, sceneComplexity: 0.26, accentDistance: 0.13, abstractionLevel: 0.15 },
    tags: ['transportation', 'bus', 'travel'],
  },
  {
    title: 'Our New Puppy',
    description: 'A family adopts a puppy and learns how to take care of it. Pet vocabulary, daily care routines, and simple commands.',
    language: 'en',
    level: 1,
    videoUrl: 'https://cdn.linguaflow.dev/content/029/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/029/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/029/subtitles.vtt',
    durationSeconds: 145,
    features: { speechSpeed: 0.38, lexicalNovelty: 0.16, grammarDensity: 0.17, subtitleDependency: 0.55, visualContextStrength: 0.75, emotionalIntensity: 0.70, narrativeDependency: 0.30, sceneComplexity: 0.22, accentDistance: 0.12, abstractionLevel: 0.12 },
    tags: ['pets', 'animals', 'family'],
  },
  {
    title: 'Autumn Leaves',
    description: 'Explore the season of autumn through changing leaves, harvest time, and cooler weather. Seasonal vocabulary in context.',
    language: 'en',
    level: 1,
    videoUrl: 'https://cdn.linguaflow.dev/content/030/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/030/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/030/subtitles.vtt',
    durationSeconds: 90,
    features: { speechSpeed: 0.36, lexicalNovelty: 0.15, grammarDensity: 0.15, subtitleDependency: 0.58, visualContextStrength: 0.72, emotionalIntensity: 0.52, narrativeDependency: 0.22, sceneComplexity: 0.20, accentDistance: 0.11, abstractionLevel: 0.13 },
    tags: ['seasons', 'autumn', 'nature'],
  },
  {
    title: 'Buying Clothes',
    description: 'Shop for clothes at a mall. Learn to ask about sizes, colors, and prices. Practice trying things on and paying.',
    language: 'en',
    level: 1,
    videoUrl: 'https://cdn.linguaflow.dev/content/031/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/031/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/031/subtitles.vtt',
    durationSeconds: 135,
    features: { speechSpeed: 0.43, lexicalNovelty: 0.20, grammarDensity: 0.20, subtitleDependency: 0.47, visualContextStrength: 0.70, emotionalIntensity: 0.50, narrativeDependency: 0.25, sceneComplexity: 0.28, accentDistance: 0.15, abstractionLevel: 0.14 },
    tags: ['shopping', 'clothing', 'conversation'],
  },
  {
    title: 'Where Is the Library?',
    description: 'A visitor asks locals for directions to various places. Multiple short conversations with map visuals to reinforce spatial language.',
    language: 'en',
    level: 1,
    videoUrl: 'https://cdn.linguaflow.dev/content/032/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/032/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/032/subtitles.vtt',
    durationSeconds: 115,
    features: { speechSpeed: 0.45, lexicalNovelty: 0.21, grammarDensity: 0.22, subtitleDependency: 0.44, visualContextStrength: 0.64, emotionalIntensity: 0.44, narrativeDependency: 0.27, sceneComplexity: 0.30, accentDistance: 0.17, abstractionLevel: 0.16 },
    tags: ['directions', 'city', 'conversation'],
  },
  {
    title: 'After-School Club',
    description: 'Students talk about their after-school activities — chess club, art class, and drama. Expressing preferences and schedules.',
    language: 'en',
    level: 1,
    videoUrl: 'https://cdn.linguaflow.dev/content/033/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/033/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/033/subtitles.vtt',
    durationSeconds: 170,
    features: { speechSpeed: 0.46, lexicalNovelty: 0.23, grammarDensity: 0.22, subtitleDependency: 0.45, visualContextStrength: 0.63, emotionalIntensity: 0.56, narrativeDependency: 0.33, sceneComplexity: 0.32, accentDistance: 0.18, abstractionLevel: 0.17 },
    tags: ['school', 'hobbies', 'social'],
  },
  {
    title: 'Basketball Game',
    description: 'Watch highlights from a community basketball game. Sports commentary with action verbs and score tracking.',
    language: 'en',
    level: 1,
    videoUrl: 'https://cdn.linguaflow.dev/content/034/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/034/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/034/subtitles.vtt',
    durationSeconds: 200,
    features: { speechSpeed: 0.50, lexicalNovelty: 0.25, grammarDensity: 0.24, subtitleDependency: 0.42, visualContextStrength: 0.71, emotionalIntensity: 0.67, narrativeDependency: 0.35, sceneComplexity: 0.34, accentDistance: 0.20, abstractionLevel: 0.16 },
    tags: ['sports', 'basketball', 'competition'],
  },
  {
    title: 'Christmas Morning',
    description: 'A family opens presents on Christmas morning. Holiday traditions, gift vocabulary, and expressions of surprise and gratitude.',
    language: 'en',
    level: 1,
    videoUrl: 'https://cdn.linguaflow.dev/content/035/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/035/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/035/subtitles.vtt',
    durationSeconds: 125,
    features: { speechSpeed: 0.39, lexicalNovelty: 0.17, grammarDensity: 0.18, subtitleDependency: 0.52, visualContextStrength: 0.74, emotionalIntensity: 0.70, narrativeDependency: 0.28, sceneComplexity: 0.25, accentDistance: 0.12, abstractionLevel: 0.12 },
    tags: ['holidays', 'christmas', 'family'],
  },
  {
    title: 'At the Pharmacy',
    description: 'Describe common symptoms and understand pharmacy instructions. Health-related vocabulary in a practical setting.',
    language: 'en',
    level: 1,
    videoUrl: 'https://cdn.linguaflow.dev/content/036/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/036/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/036/subtitles.vtt',
    durationSeconds: 140,
    features: { speechSpeed: 0.42, lexicalNovelty: 0.24, grammarDensity: 0.23, subtitleDependency: 0.48, visualContextStrength: 0.60, emotionalIntensity: 0.46, narrativeDependency: 0.30, sceneComplexity: 0.28, accentDistance: 0.16, abstractionLevel: 0.20 },
    tags: ['health', 'pharmacy', 'conversation'],
  },
  {
    title: 'Riding the Train',
    description: 'Plan a train trip from buying tickets to arriving at your destination. Timetables, platforms, and announcements.',
    language: 'en',
    level: 1,
    videoUrl: 'https://cdn.linguaflow.dev/content/037/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/037/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/037/subtitles.vtt',
    durationSeconds: 155,
    features: { speechSpeed: 0.44, lexicalNovelty: 0.20, grammarDensity: 0.19, subtitleDependency: 0.50, visualContextStrength: 0.67, emotionalIntensity: 0.48, narrativeDependency: 0.32, sceneComplexity: 0.30, accentDistance: 0.15, abstractionLevel: 0.16 },
    tags: ['transportation', 'train', 'travel'],
  },
  {
    title: 'At the Dog Park',
    description: 'Dog owners chat while their pets play. Pet care vocabulary, casual conversation patterns, and descriptive language.',
    language: 'en',
    level: 1,
    videoUrl: 'https://cdn.linguaflow.dev/content/038/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/038/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/038/subtitles.vtt',
    durationSeconds: 110,
    features: { speechSpeed: 0.47, lexicalNovelty: 0.19, grammarDensity: 0.20, subtitleDependency: 0.46, visualContextStrength: 0.73, emotionalIntensity: 0.62, narrativeDependency: 0.26, sceneComplexity: 0.26, accentDistance: 0.18, abstractionLevel: 0.14 },
    tags: ['pets', 'dogs', 'casual-conversation'],
  },
  {
    title: 'Spring Gardening',
    description: 'Plant flowers and vegetables in a spring garden. Seasonal vocabulary, action sequences, and nature words.',
    language: 'en',
    level: 1,
    videoUrl: 'https://cdn.linguaflow.dev/content/039/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/039/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/039/subtitles.vtt',
    durationSeconds: 130,
    features: { speechSpeed: 0.37, lexicalNovelty: 0.16, grammarDensity: 0.16, subtitleDependency: 0.54, visualContextStrength: 0.75, emotionalIntensity: 0.54, narrativeDependency: 0.24, sceneComplexity: 0.23, accentDistance: 0.11, abstractionLevel: 0.13 },
    tags: ['seasons', 'spring', 'gardening'],
  },
  {
    title: 'Summer Vacation Plans',
    description: 'Friends discuss their summer plans — beach trips, camping, and visiting family. Future tense and planning language.',
    language: 'en',
    level: 1,
    videoUrl: 'https://cdn.linguaflow.dev/content/040/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/040/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/040/subtitles.vtt',
    durationSeconds: 165,
    features: { speechSpeed: 0.48, lexicalNovelty: 0.22, grammarDensity: 0.22, subtitleDependency: 0.44, visualContextStrength: 0.65, emotionalIntensity: 0.58, narrativeDependency: 0.35, sceneComplexity: 0.31, accentDistance: 0.17, abstractionLevel: 0.18 },
    tags: ['seasons', 'summer', 'travel'],
  },
]

const level2Items: SeedContentItem[] = [
  {
    title: 'Backpacking Through Europe',
    description: 'A travel vlog about backpacking across three European countries. Cultural observations, travel logistics, and personal reflections.',
    language: 'en',
    level: 2,
    videoUrl: 'https://cdn.linguaflow.dev/content/041/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/041/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/041/subtitles.vtt',
    durationSeconds: 350,
    features: { speechSpeed: 0.58, lexicalNovelty: 0.32, grammarDensity: 0.32, subtitleDependency: 0.35, visualContextStrength: 0.50, emotionalIntensity: 0.65, narrativeDependency: 0.40, sceneComplexity: 0.38, accentDistance: 0.20, abstractionLevel: 0.22 },
    tags: ['travel', 'europe', 'culture'],
  },
  {
    title: 'Local News: Community Garden Opens',
    description: 'A short news segment about a new community garden. News reporting style with formal language and community vocabulary.',
    language: 'en',
    level: 2,
    videoUrl: 'https://cdn.linguaflow.dev/content/042/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/042/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/042/subtitles.vtt',
    durationSeconds: 240,
    features: { speechSpeed: 0.62, lexicalNovelty: 0.35, grammarDensity: 0.35, subtitleDependency: 0.30, visualContextStrength: 0.45, emotionalIntensity: 0.52, narrativeDependency: 0.42, sceneComplexity: 0.40, accentDistance: 0.22, abstractionLevel: 0.25 },
    tags: ['news', 'community', 'environment'],
  },
  {
    title: 'First Day at a New Job',
    description: 'Navigate the challenges of starting a new office job. Workplace vocabulary, formal introductions, and professional communication.',
    language: 'en',
    level: 2,
    videoUrl: 'https://cdn.linguaflow.dev/content/043/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/043/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/043/subtitles.vtt',
    durationSeconds: 420,
    features: { speechSpeed: 0.60, lexicalNovelty: 0.38, grammarDensity: 0.38, subtitleDependency: 0.32, visualContextStrength: 0.42, emotionalIntensity: 0.58, narrativeDependency: 0.45, sceneComplexity: 0.42, accentDistance: 0.25, abstractionLevel: 0.28 },
    tags: ['workplace', 'career', 'professional'],
  },
  {
    title: 'Diwali: Festival of Lights',
    description: 'Learn about the Indian festival of Diwali through a family celebration. Cultural traditions, rituals, and festive vocabulary.',
    language: 'en',
    level: 2,
    videoUrl: 'https://cdn.linguaflow.dev/content/044/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/044/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/044/subtitles.vtt',
    durationSeconds: 300,
    features: { speechSpeed: 0.56, lexicalNovelty: 0.30, grammarDensity: 0.30, subtitleDependency: 0.38, visualContextStrength: 0.55, emotionalIntensity: 0.72, narrativeDependency: 0.38, sceneComplexity: 0.36, accentDistance: 0.18, abstractionLevel: 0.20 },
    tags: ['culture', 'traditions', 'festival'],
  },
  {
    title: 'Making New Friends',
    description: 'A story about two strangers who become friends at a language exchange meetup. Social dynamics, conversation strategies, and emotional language.',
    language: 'en',
    level: 2,
    videoUrl: 'https://cdn.linguaflow.dev/content/045/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/045/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/045/subtitles.vtt',
    durationSeconds: 380,
    features: { speechSpeed: 0.57, lexicalNovelty: 0.33, grammarDensity: 0.33, subtitleDependency: 0.36, visualContextStrength: 0.48, emotionalIntensity: 0.70, narrativeDependency: 0.48, sceneComplexity: 0.37, accentDistance: 0.19, abstractionLevel: 0.24 },
    tags: ['friendship', 'social', 'emotions'],
  },
  {
    title: 'Saving the Ocean',
    description: 'A documentary-style video about ocean pollution and conservation efforts. Environmental vocabulary and persuasive language.',
    language: 'en',
    level: 2,
    videoUrl: 'https://cdn.linguaflow.dev/content/046/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/046/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/046/subtitles.vtt',
    durationSeconds: 480,
    features: { speechSpeed: 0.64, lexicalNovelty: 0.40, grammarDensity: 0.40, subtitleDependency: 0.28, visualContextStrength: 0.52, emotionalIntensity: 0.68, narrativeDependency: 0.44, sceneComplexity: 0.44, accentDistance: 0.28, abstractionLevel: 0.30 },
    tags: ['environment', 'ocean', 'conservation'],
  },
  {
    title: 'A Week in Japan',
    description: 'Travel diary from a week-long trip to Japan. Cultural comparisons, travel anecdotes, and descriptive language about new experiences.',
    language: 'en',
    level: 2,
    videoUrl: 'https://cdn.linguaflow.dev/content/047/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/047/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/047/subtitles.vtt',
    durationSeconds: 400,
    features: { speechSpeed: 0.59, lexicalNovelty: 0.34, grammarDensity: 0.34, subtitleDependency: 0.34, visualContextStrength: 0.53, emotionalIntensity: 0.62, narrativeDependency: 0.46, sceneComplexity: 0.40, accentDistance: 0.22, abstractionLevel: 0.26 },
    tags: ['travel', 'japan', 'culture'],
  },
  {
    title: 'Breaking News: Storm Warning',
    description: 'A news broadcast about an approaching storm with safety instructions. Urgent tone, formal language, and safety vocabulary.',
    language: 'en',
    level: 2,
    videoUrl: 'https://cdn.linguaflow.dev/content/048/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/048/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/048/subtitles.vtt',
    durationSeconds: 180,
    features: { speechSpeed: 0.68, lexicalNovelty: 0.42, grammarDensity: 0.42, subtitleDependency: 0.25, visualContextStrength: 0.40, emotionalIntensity: 0.75, narrativeDependency: 0.50, sceneComplexity: 0.45, accentDistance: 0.30, abstractionLevel: 0.32 },
    tags: ['news', 'weather', 'safety'],
  },
  {
    title: 'Team Meeting at Work',
    description: 'Observe a typical team meeting at a tech company. Professional jargon, meeting etiquette, and collaborative language.',
    language: 'en',
    level: 2,
    videoUrl: 'https://cdn.linguaflow.dev/content/049/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/049/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/049/subtitles.vtt',
    durationSeconds: 360,
    features: { speechSpeed: 0.63, lexicalNovelty: 0.36, grammarDensity: 0.36, subtitleDependency: 0.30, visualContextStrength: 0.38, emotionalIntensity: 0.55, narrativeDependency: 0.42, sceneComplexity: 0.43, accentDistance: 0.24, abstractionLevel: 0.30 },
    tags: ['workplace', 'meeting', 'professional'],
  },
  {
    title: 'Recycling in Our Town',
    description: 'How a small town implemented a recycling program. Community action, environmental terms, and cause-and-effect language.',
    language: 'en',
    level: 2,
    videoUrl: 'https://cdn.linguaflow.dev/content/050/video.mp4',
    thumbnailUrl: 'https://cdn.linguaflow.dev/content/050/thumb.jpg',
    subtitleUrl: 'https://cdn.linguaflow.dev/content/050/subtitles.vtt',
    durationSeconds: 280,
    features: { speechSpeed: 0.55, lexicalNovelty: 0.31, grammarDensity: 0.31, subtitleDependency: 0.37, visualContextStrength: 0.54, emotionalIntensity: 0.60, narrativeDependency: 0.40, sceneComplexity: 0.38, accentDistance: 0.17, abstractionLevel: 0.28 },
    tags: ['environment', 'recycling', 'community'],
  },
]

export const seedData: SeedContentItem[] = [...level0Items, ...level1Items, ...level2Items]
