import type { ContentItem } from '@/types/content'

export const mockContent: ContentItem[] = [
  {
    id: 'cnt_001',
    videoUrl: '/content/cooking-morning.mp4',
    subtitleUrl: '/content/cooking-morning.vtt',
    features: {
      speechSpeed: 0.6,
      lexicalNovelty: 0.15,
      grammarDensity: 0.2,
      subtitleDependency: 0.3,
      visualContextStrength: 0.85,
      emotionalIntensity: 0.3,
      narrativeDependency: 0.2,
      sceneComplexity: 0.25,
      accentDistance: 0.1,
      abstractionLevel: 0.1,
    },
    level: 0,
    language: 'en',
    title: 'Morning Kitchen',
    description: 'A quiet morning making breakfast',
    duration: 45,
    thumbnailUrl: '/content/cooking-morning-thumb.jpg',
  },
  {
    id: 'cnt_002',
    videoUrl: '/content/walk-park.mp4',
    subtitleUrl: '/content/walk-park.vtt',
    features: {
      speechSpeed: 0.65,
      lexicalNovelty: 0.18,
      grammarDensity: 0.25,
      subtitleDependency: 0.35,
      visualContextStrength: 0.8,
      emotionalIntensity: 0.35,
      narrativeDependency: 0.25,
      sceneComplexity: 0.3,
      accentDistance: 0.12,
      abstractionLevel: 0.15,
    },
    level: 0,
    language: 'en',
    title: 'Park Walk',
    description: 'Strolling through the neighborhood park',
    duration: 52,
    thumbnailUrl: '/content/walk-park-thumb.jpg',
  },
  {
    id: 'cnt_003',
    videoUrl: '/content/coffee-chat.mp4',
    subtitleUrl: '/content/coffee-chat.vtt',
    features: {
      speechSpeed: 0.7,
      lexicalNovelty: 0.2,
      grammarDensity: 0.3,
      subtitleDependency: 0.35,
      visualContextStrength: 0.75,
      emotionalIntensity: 0.4,
      narrativeDependency: 0.3,
      sceneComplexity: 0.35,
      accentDistance: 0.15,
      abstractionLevel: 0.2,
    },
    level: 0,
    language: 'en',
    title: 'Coffee Chat',
    description: 'Casual conversation over coffee',
    duration: 60,
    thumbnailUrl: '/content/coffee-chat-thumb.jpg',
  },
  {
    id: 'cnt_004',
    videoUrl: '/content/grocery-run.mp4',
    subtitleUrl: '/content/grocery-run.vtt',
    features: {
      speechSpeed: 0.72,
      lexicalNovelty: 0.25,
      grammarDensity: 0.32,
      subtitleDependency: 0.4,
      visualContextStrength: 0.82,
      emotionalIntensity: 0.3,
      narrativeDependency: 0.28,
      sceneComplexity: 0.38,
      accentDistance: 0.18,
      abstractionLevel: 0.22,
    },
    level: 1,
    language: 'en',
    title: 'Grocery Run',
    description: 'Picking up ingredients for dinner',
    duration: 55,
    thumbnailUrl: '/content/grocery-run-thumb.jpg',
  },
  {
    id: 'cnt_005',
    videoUrl: '/content/street-music.mp4',
    subtitleUrl: '/content/street-music.vtt',
    features: {
      speechSpeed: 0.75,
      lexicalNovelty: 0.28,
      grammarDensity: 0.35,
      subtitleDependency: 0.42,
      visualContextStrength: 0.7,
      emotionalIntensity: 0.55,
      narrativeDependency: 0.35,
      sceneComplexity: 0.4,
      accentDistance: 0.2,
      abstractionLevel: 0.25,
    },
    level: 1,
    language: 'en',
    title: 'Street Music',
    description: 'Discovering a street performer',
    duration: 48,
    thumbnailUrl: '/content/street-music-thumb.jpg',
  },
  {
    id: 'cnt_006',
    videoUrl: '/content/bookshop.mp4',
    subtitleUrl: '/content/bookshop.vtt',
    features: {
      speechSpeed: 0.78,
      lexicalNovelty: 0.32,
      grammarDensity: 0.38,
      subtitleDependency: 0.45,
      visualContextStrength: 0.68,
      emotionalIntensity: 0.35,
      narrativeDependency: 0.4,
      sceneComplexity: 0.42,
      accentDistance: 0.22,
      abstractionLevel: 0.3,
    },
    level: 1,
    language: 'en',
    title: 'The Bookshop',
    description: 'Browsing shelves on a rainy afternoon',
    duration: 65,
    thumbnailUrl: '/content/bookshop-thumb.jpg',
  },
  {
    id: 'cnt_007',
    videoUrl: '/content/train-ride.mp4',
    subtitleUrl: '/content/train-ride.vtt',
    features: {
      speechSpeed: 0.8,
      lexicalNovelty: 0.35,
      grammarDensity: 0.4,
      subtitleDependency: 0.48,
      visualContextStrength: 0.65,
      emotionalIntensity: 0.4,
      narrativeDependency: 0.45,
      sceneComplexity: 0.45,
      accentDistance: 0.25,
      abstractionLevel: 0.35,
    },
    level: 1,
    language: 'en',
    title: 'Train Ride',
    description: 'Conversations on a cross-country train',
    duration: 70,
    thumbnailUrl: '/content/train-ride-thumb.jpg',
  },
  {
    id: 'cnt_008',
    videoUrl: '/content/night-market.mp4',
    subtitleUrl: '/content/night-market.vtt',
    features: {
      speechSpeed: 0.85,
      lexicalNovelty: 0.4,
      grammarDensity: 0.45,
      subtitleDependency: 0.5,
      visualContextStrength: 0.6,
      emotionalIntensity: 0.5,
      narrativeDependency: 0.48,
      sceneComplexity: 0.5,
      accentDistance: 0.28,
      abstractionLevel: 0.38,
    },
    level: 2,
    language: 'en',
    title: 'Night Market',
    description: 'Haggling and exploring the night bazaar',
    duration: 58,
    thumbnailUrl: '/content/night-market-thumb.jpg',
  },
  {
    id: 'cnt_009',
    videoUrl: '/content/art-studio.mp4',
    subtitleUrl: '/content/art-studio.vtt',
    features: {
      speechSpeed: 0.82,
      lexicalNovelty: 0.42,
      grammarDensity: 0.48,
      subtitleDependency: 0.52,
      visualContextStrength: 0.72,
      emotionalIntensity: 0.45,
      narrativeDependency: 0.5,
      sceneComplexity: 0.48,
      accentDistance: 0.3,
      abstractionLevel: 0.42,
    },
    level: 2,
    language: 'en',
    title: 'Art Studio',
    description: 'An artist explains their creative process',
    duration: 75,
    thumbnailUrl: '/content/art-studio-thumb.jpg',
  },
  {
    id: 'cnt_010',
    videoUrl: '/content/rooftop.mp4',
    subtitleUrl: '/content/rooftop.vtt',
    features: {
      speechSpeed: 0.88,
      lexicalNovelty: 0.45,
      grammarDensity: 0.5,
      subtitleDependency: 0.55,
      visualContextStrength: 0.58,
      emotionalIntensity: 0.48,
      narrativeDependency: 0.52,
      sceneComplexity: 0.52,
      accentDistance: 0.32,
      abstractionLevel: 0.45,
    },
    level: 2,
    language: 'en',
    title: 'Rooftop Views',
    description: 'Friends share stories at sunset',
    duration: 80,
    thumbnailUrl: '/content/rooftop-thumb.jpg',
  },
]
